### ISSUE TITLE
Watcom call replacement

### ISSUE THREAD

**Issue by Arcnor** [FunkyFr3sh/petool#2]
Hey, this is a very cool project, thanks for making it available!

I'm trying to patch an executable made with the Watcom compiler using the default register calling convention. I know you have a macro to deal with Watcom functions, but it seems that macro is only useful for calling them, not when replacing them.

I'm not very well versed in GCC inline assembly, but maybe you have an idea about how to make this usecase work.

My approach has been the following, for example when replacing a function with 3 parameters passed by register (this can change depending on the type of the parameters, but I'm ignoring that for now):

```
CALL(0xZZZZZZZZ, _myWatcomFunc);

EXTERN_C void myWatcomFunc(int arg0, int arg1, int arg2) {
	asm (
		"mov %0, eax\n\t"
		"mov %1, edx\n\t"
		"mov %2, ebx\n\t"
	: "=r" (arg0), "=r" (arg1), "=r" (arg2)
	: /* No Inputs */
	);

	...
}
```

This *seems* to work, and I'd be happy to manually "tag" every function at the very beginning with a macro like `WATCOM_3_ARG(arg0, arg1, arg2)` to replace that asm block, but I'm not sure if this works just by chance (GCC doesn't know it cannot touch those registers before my code runs for example) and also not sure if there is a better way to do this.

In any case, thanks again!

**Comment by FunkyFr3sh** [comment]
Hm, yeah that's a cool idea but there's a chance that it could fail.

Something like this here should be a bit more failsafe but I'll have to put some more thought into it

```
CALL(0xZZZZZZZZ, _myWatcomFunc);

EXTERN_C void __attribute__((naked)) myWatcomFunc() {
	asm (
                  "push ecx\n\t"

                  "push ebx\n\t"
                  "push edx\n\t"
                  "push eax\n\t"
                  "call _myWatcomFunc_dst\n\t"
                  "add esp, 12\n\t"

                  "pop ecx\n\t"
                  "ret\n\t"
	);
}

EXTERN_C void myWatcomFunc_dst(int arg0, int arg1, int arg2)
{

}
```

Would be cool to have a macro for it (of course one that can handle more than 4 args as well)

**Comment by Arcnor** [comment]
Hey, thanks for the response!

Do you say it's more failsafe because the compiler will not touch any registers for an empty function body?

If that's the reason, will it be possible to avoid the call by making GCC realize the registers are used, maybe with some of those input/output flags you can give it?

Also, although I agree we of course need a macro that can handle more than 4 args, my reason for having specific argument ones was to avoid the performance penalty, the current ASM macro for calling Watcom functions does a lot and it adds up when you have a lot of functions I think (although one can argue that in today's world that might be a non-issue, but anyway...) so having a macro that dealt with exactly one argument for example could be much simplified, code wise.

**Comment by FunkyFr3sh** [comment]
> Do you say it's more failsafe because the compiler will not touch any registers for an empty function body?

Yes
Although, I couldn't provide you with a example that could break your solution... I'm just not 100% sure here if we can rely on the compiler not messing with them. 

The other reason is that in cdecl eax, ecx and edx are caller-saved and they will very highly likely lose their values. With watcom there's a chance the compiler may place a value into these register and then tries to use the register after the function call (That's why the push/pop of ecx in my example). However, I only saw such cases happening twice in many years (it was in C&C Red Alert).

> If that's the reason, will it be possible to avoid the call by making GCC realize the registers are used, maybe with some of those input/output flags you can give it?

Not sure if there's a better way than __attribute__((naked)). You could also do it without the function call and place everything in the naked function instead

> Also, although I agree we of course need a macro that can handle more than 4 args, my reason for having specific argument ones was to avoid the performance penalty, the current ASM macro for calling Watcom functions does a lot and it adds up when you have a lot of functions I think (although one can argue that in today's world that might be a non-issue, but anyway...) so having a macro that dealt with exactly one argument for example could be much simplified, code wise.

Yeah, it depends on where it's used. But in 99% of the cases it shouldn't matter. I usually run the games with the visual studio profiler and rewrite the slow code by hand using SSE, have not had a case yet where the watcall hack was an issue

**Comment by Arcnor** [comment]
Hey sorry, I thought I replied to this:

> Not sure if there's a better way than attribute((naked)). You could also do it without the function call and place everything in the naked function instead

Can you elaborate? I'm not sure I follow, I thought we needed the call to avoid GCC messing with the registers, if we add everything to the naked function, aren't we at step 1 again?

**Comment by FunkyFr3sh** [comment]
We need the naked function to avoid GCC messing with the registers, the call is there to avoid dealing with the limitations of the naked function.

From GCC docs:
> **naked**
> This attribute allows the compiler to construct the requisite function declaration, while allowing the body of the function to be assembly code. The specified function will not have prologue/epilogue sequences generated by the compiler. Only basic asm statements can safely be included in naked functions (see [Basic Asm](https://gcc.gnu.org/onlinedocs/gcc-6.1.0/gcc/Basic-Asm.html#Basic-Asm)). While using extended asm or a mixture of basic asm and C code may appear to work, they cannot be depended upon to work reliably and are not supported.

If you really want to avoid the call then you could stick to asm in the naked function instead or you take the risk of `cannot be depended upon to work reliably and are not supported` and mix it with C code

**Comment by Arcnor** [comment]
Having the call is not a big deal I think, I've been using your solution and it works just fine (so far) :). I just need to create either a few macros for it, or try to create one uber-macro like the one you have for Watcom callers right now.

**Comment by FunkyFr3sh** [comment]
Yeah, maybe something like this:

```
CALL_WATCOM(0xZZZZZZZZ, _myWatcomFunc, 3);

EXTERN_C void myWatcomFunc(int arg0, int arg1, int arg2)
{

}
```

`CALL_WATCOM` would then pick the right macro depending on the arg count (arg 3)

```
// 6 args (not actually tested!)
EXTERN_C void __attribute__((naked)) myWatcomFunc_tmp_watcom() {
	asm (
                  "push ebp\n\t"
                  "mov ebp, esp\n\t"

                  "push dword[ebp+8]\n\t"
                  "push dword[ebp+4]\n\t"
                  "push ecx\n\t"
                  "push ebx\n\t"
                  "push edx\n\t"
                  "push eax\n\t"
                  "call _myWatcomFunc\n\t"
                  "add esp, 24\n\t"

                  "pop ebp\n\t"
                  "ret 8\n\t"
	);
}
```
```
// 5 args (not actually tested!)
EXTERN_C void __attribute__((naked)) myWatcomFunc_tmp_watcom() {
	asm (
                  "push ebp\n\t"
                  "mov ebp, esp\n\t"

                  "push dword[ebp+4]\n\t"
                  "push ecx\n\t"
                  "push ebx\n\t"
                  "push edx\n\t"
                  "push eax\n\t"
                  "call _myWatcomFunc\n\t"
                  "add esp, 20\n\t"

                  "pop ebp\n\t"
                  "ret 4\n\t"
	);
}
```
```
// 4 args
EXTERN_C void __attribute__((naked)) myWatcomFunc_tmp_watcom() {
	asm (
                  "push ecx\n\t"
                  "push ebx\n\t"
                  "push edx\n\t"
                  "push eax\n\t"
                  "call _myWatcomFunc\n\t"
                  "add esp, 16\n\t"

                  "ret\n\t"
	);
}
```
```
// 3 args
EXTERN_C void __attribute__((naked)) myWatcomFunc_tmp_watcom() {
	asm (
                  "push ecx\n\t"

                  "push ebx\n\t"
                  "push edx\n\t"
                  "push eax\n\t"
                  "call _myWatcomFunc\n\t"
                  "add esp, 12\n\t"

                  "pop ecx\n\t"
                  "ret\n\t"
	);
}
```
```
// 2 args
EXTERN_C void __attribute__((naked)) myWatcomFunc_tmp_watcom() {
	asm (
                  "push ecx\n\t"
                  "push ebx\n\t"

                  "push edx\n\t"
                  "push eax\n\t"
                  "call _myWatcomFunc\n\t"
                  "add esp, 8\n\t"

                  "pop ebx\n\t"
                  "pop ecx\n\t"
                  "ret\n\t"
	);
}
```
```
// 1 arg
EXTERN_C void __attribute__((naked)) myWatcomFunc_tmp_watcom() {
	asm (
                  "push ecx\n\t"
                  "push ebx\n\t"
                  "push edx\n\t"

                  "push eax\n\t"
                  "call _myWatcomFunc\n\t"
                  "add esp, 4\n\t"

                  "pop edx\n\t"
                  "pop ebx\n\t"
                  "pop ecx\n\t"
                  "ret\n\t"
	);
}
```
```
// 0 args
EXTERN_C void __attribute__((naked)) myWatcomFunc_tmp_watcom() {
	asm (
                  "push ecx\n\t"
                  "push ebx\n\t"
                  "push edx\n\t"

                  "call _myWatcomFunc\n\t"

                  "pop edx\n\t"
                  "pop ebx\n\t"
                  "pop ecx\n\t"
                  "ret\n\t"
	);
}
```

**Comment by FunkyFr3sh** [comment]
Just tested it, seems to work fine. Added the new `CALL_WATCOM` macro:

```
CALL_WATCOM(0xZZZZZZZZ, _myWatcomFunc, 3);

EXTERN_C void myWatcomFunc(int arg0, int arg1, int arg2)
{

}
```

Supports up to 10 args currently, but it's easy to extend it if needed.

https://github.com/FunkyFr3sh/petool/blob/master/res/inc/macros/patch.h



Also, the `SETWATGLOB` macro is a lot faster now (removed watcall.asm)

https://github.com/FunkyFr3sh/petool/blob/master/res/inc/macros/setsym.h

**Comment by Arcnor** [comment]
Oh, that's a nice way to improve the old macro, for sure. And 10 args is probably plenty for the new one, will give it a try very shortly, thanks!

**Comment by Arcnor** [comment]
Seems to work fine, although coincidentally all my tested calls have been the 3 argument variant, but looking at the code I don't see why it won't work for the rest. I'll close this now, and will comment back if I find any issues there, thanks for adding this!

**Comment by FunkyFr3sh** [comment]
Had to do some additional changes to support 6byte call instructions as well

```
//old
CALL_WATCOM(0xZZZZZZZZ, _myWatcomFunc, 3);

//new
CALL(0xZZZZZZZZ, _myWatcomFunc, 3);
CALL_NOP(0xZZZZZZZZ, _myWatcomFunc, 3);
```

And also got rid of `SETWATGLOB`
```
//old
SETWATGLOB(0x004D500, doMagic, 4);
//new
SETCGLOB(0x004D500, doMagic, 4);
```

**Comment by Arcnor** [comment]
Nice, will update soon, thanks for the heads up 🙂
